name: Build Domino EXE
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Code herunterladen
      uses: actions/checkout@v4
    - name: Python einrichten
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Bausteine installieren
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pygame
    - name: EXE Datei herstellen
      run: |
        pyinstaller --onefile --noconsole "domino gui jackpot-old.py"
    - name: Fertiges Spiel bereitstellen
      uses: actions/upload-artifact@v4
      with:
        name: Domino-Spiel-Windows
        path: dist/domino gui jackpot-old.exe
